CREATE DATABASE IF NOT EXISTS arcadia_db;

USE arcadia_db;

CREATE TABLE IF NOT EXISTS scores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    game_name VARCHAR(50) NOT NULL,
    score INT NOT NULL,
    played_at DATETIME DEFAULT CURRENT_TIMESTAMP
);